#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The table behind the 6VB's counter-0 oscillator (rtl/sound/sente6vb_c0timer.sv).

    python scripts/gen_c0_steptab.py          # writes rtl/sound/sente6vb_steptab.sv
    python scripts/gen_c0_steptab.py --check  # the error report only

MAME clocks the calibration flip-flop from a timer at a voice's frequency
(sente6vb.cpp update_counter_0_timer). cem3394.cpp gives the two laws, with
cv = dac * 8/4096 - 4:

    vco    f = z_v * 2^(-cv / 0.75)    z_v = 1.3 / (5 * R_vco * C_vco)
    filter f = z_f * 2^(-cv / 0.375)   z_f = 4.3e-5 / C_vcf

Both are C * 2^(-x/384), with x = dac for the oscillator and 2*dac for the
filter. The RTL splits x = 384*q + r and reads a 24-bit mantissa for r, so the
NCO step is a table read and a shift, with no multiply or exp:

    step = ({tab[type][r], 16'b0} >> (q + SH[type]))     2^44 = one period

The report is the worst error of the resulting period against MAME's, over
every DAC code counter 1 can measure, in counts of the 2 MHz clock over the
longest window that fits in counter 1 (at most 16 periods, the routine's most).
"""
import argparse
import math
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "rtl" / "sound" / "sente6vb_steptab.sv"

CLK = 40e6
ACC = 44
R_VCO, C_VCO, C_VCF = 301e3, 2e-9, 33e-9          # sente6vb.cpp components
Z = (1.3 / (5.0 * R_VCO * C_VCO), 4.3e-5 / C_VCF)   # vco, filter
DIV = (0.75, 0.375)


def mame_freq(typ, dac):
    cv = dac * (8.0 / 4096.0) - 4.0
    return Z[typ] * 2.0 ** (-cv / DIV[typ])


def scale(typ):
    """S such that step(x) = S * 2^(-x/384), and E so that S / 2^E < 2^24."""
    c = Z[typ] * 2.0 ** (4.0 / DIV[typ])            # f at dac 0
    s = c / CLK * 2.0 ** ACC
    e = math.ceil(math.log2(s)) - 24
    return s, e


def table(typ):
    s, e = scale(typ)
    return [round(s * 2.0 ** (-r / 384.0) / 2.0 ** e) for r in range(384)]


def rtl_step(tabs, typ, dac):
    x = dac if typ == 0 else 2 * dac
    q, r = divmod(x, 384)
    sh = q + (16 - scale(typ)[1])
    return (tabs[typ][r] << 16) >> sh


def check(tabs):
    worst = (0.0, None)
    for typ in (0, 1):
        for dac in range(4096):
            f = mame_freq(typ, dac)
            if f >= CLK / 2:
                continue
            # Periods per window: up to 16, as many as counter 1 can hold.
            n = min(16, int(65535 * f / 2e6))
            if n == 0:
                continue                              # counter 1 cannot measure it
            step = rtl_step(tabs, typ, dac)
            period = 2.0 ** ACC / step / CLK          # seconds, the NCO's mean
            err = abs(period - 1.0 / f) * n * 2e6
            if err > worst[0]:
                worst = (err, (("vco", "filter")[typ], dac, f))
    return worst


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    tabs = [table(0), table(1)]
    for t in tabs:
        assert max(t) < (1 << 24), max(t)
    err, where = check(tabs)
    print(f"worst window error: {err:.2e} counts of 2 MHz at {where}")
    print(f"shift offsets: vco {16 - scale(0)[1]}, filter {16 - scale(1)[1]}")
    if a.check:
        return 0
    rows = []
    for typ in (0, 1):
        for r, v in enumerate(tabs[typ]):
            rows.append(f"            10'd{typ * 512 + r}: q <= 24'h{v:06X};")
    OUT.write_text(f"""// SPDX-License-Identifier: GPL-3.0-or-later
//
// GENERATED by scripts/gen_c0_steptab.py -- do not edit. The derivation and
// the error report are in that script.
//
// Mantissa of the counter-0 NCO step, C * 2^(-r/384), for r in 0..383.
// Address {{type, r}}: type 0 the oscillator law, 1 the filter law.
// Registered read, so Quartus can put it in block RAM.

module sente6vb_steptab (
    input  logic        clk,
    input  logic [9:0]  addr,
    output logic [23:0] q
);
    always_ff @(posedge clk) begin
        case (addr)
{chr(10).join(rows)}
            default: q <= 24'h0;
        endcase
    end
endmodule
""", newline="\n")
    print(f"-> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
